document.writeln("<SCRIPT language=JavaScript type=text\/JavaScript> ");
document.writeln("function quickreply(){");
document.writeln("if(formreply.body.value==\'\')");
document.writeln("{ ");
document.writeln("        alert(\'请输入排版内容!\');");
document.writeln("   formreply.body.focus(); ");
document.writeln("   return false;");
document.writeln("  }else{ ");
document.writeln("        return true;");
document.writeln("  }");
document.writeln("}");
document.writeln("function format()");
document.writeln("{");
document.writeln("        var body = \"\\n\"+document.getElementById(\"thebody\").value;");
document.writeln("        body = body.replace(\/ |　\/ig,\"\");");
document.writeln("        body = body.replace(\/\\r\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\/ig,\"\\n\\n　　\");		");
document.writeln("        body = body.replace(\"\\n\\n\",\"\");");
document.writeln("        document.getElementById(\"thebody\").value=body;");
document.writeln("}");
document.writeln(" ");
document.writeln("<\/SCRIPT>");
document.writeln("<SCRIPT language=JavaScript type=text\/JavaScript> ");
document.writeln("function quickreply(){");
document.writeln("if(formreply.body.value==\'\')");
document.writeln("{ ");
document.writeln("        alert(\'请输入回复内容!\');");
document.writeln("   formreply.body.focus(); ");
document.writeln("   return false;");
document.writeln("  }else{ ");
document.writeln("        return true;");
document.writeln("  }");
document.writeln("}");
document.writeln("function format2()");
document.writeln("{");
document.writeln("        var body = \"\\n\"+document.getElementById(\"thebody\").value;");
document.writeln("        body = body.replace(\/ |　\/ig,\"\");");
document.writeln("        body = body.replace(\/\\r\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\/ig,\"  \\n\");");
document.writeln("        body = body.replace(\"\\n\\n\",\"\\n\");");
document.writeln("        document.getElementById(\"thebody\").value=body;");
document.writeln("}");
document.writeln("function format3()");
document.writeln("{");
document.writeln("        var body = \"\\n\"+document.getElementById(\"thebody\").value;");
document.writeln("        body = body.replace(\/ |　\/ig,\"\");");
document.writeln("        body = body.replace(\/\\r\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\\n\/ig,\"\\n\");");
document.writeln("        body = body.replace(\/\\n\/ig,\"\\n\\n\");");
document.writeln("        body = body.replace(\"\\n\\n\",\"\");");
document.writeln("        document.getElementById(\"thebody\").value=body;");
document.writeln("}");
document.writeln("function format4()");
document.writeln("{");
document.writeln("        var body = document.getElementById(\"thebody\").value;");
document.writeln("        for (var ii=0; 100>ii;ii++)");
document.writeln(" {");
document.writeln("  body = body.replace(\"\",\"\");  \/\/去除全角空格");
document.writeln("  body = body.replace(\",\",\"，\");  \/\/替换英文标点 ");
document.writeln("  body = body.replace(\"......\",\"……\"); ");
document.writeln("  body = body.replace(\"。。。。。。\",\"……\"); ");
document.writeln("  body = body.replace(\"?\",\"？\"); ");
document.writeln("  body = body.replace(\".\",\"。\");  ");
document.writeln("  body = body.replace(\";\",\"；\");  ");
document.writeln("  body = body.replace(\":\",\"：\"); ");
document.writeln("  body = body.replace(\"!\",\"！\"); ");
document.writeln("  body = body.replace(\"(\",\"（\"); ");
document.writeln("  body = body.replace(\")\",\"）\"); ");
document.writeln("  body = body.replace(\"----\",\"——\"); ");
document.writeln("  body = body.replace(\"--\",\"——\"); ");
document.writeln("  body = body.replace(\"[\",\"［\"); ");
document.writeln("  body = body.replace(\"]\",\"］\"); ");
document.writeln("  }");
document.writeln("        document.getElementById(\"thebody\").value=body;");
document.writeln("}");
document.writeln("<\/SCRIPT>");
document.writeln(" ");
document.writeln("<SCRIPT language=JavaScript> ");
document.writeln("function copy(ob){");
document.writeln("var obj=findObj(ob); if (obj) { ");
document.writeln("obj.select();js=obj.createTextRange();js.execCommand(\"Copy\");}");
document.writeln("}");
document.writeln("function paste(ob) {");
document.writeln("	var obj=findObj(ob); if (obj) { ");
document.writeln("	obj.select();js=obj.createTextRange();js.execCommand(\"Paste\");}");
document.writeln("}");
document.writeln("function findObj(n, d) { ");
document.writeln("var p,i,x; if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {");
document.writeln("d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}");
document.writeln("if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];");
document.writeln("for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=findObj(n,d.layers[i].document);");
document.writeln("if(!x && document.getElementById) x=document.getElementById(n); return x;");
document.writeln("}");
document.writeln("<\/SCRIPT>");
document.writeln(" ");
document.writeln("<\/SCRIPT><script language=\"javascript\">");
document.writeln("function chklen() {");
document.writeln("  var strlen;");
document.writeln("  strlen= KKsForm.Content.value.length;");
document.writeln("  alert(\"目前长度\" + strlen + \"文字\\n\");");
document.writeln("  return;");
document.writeln("  }");
document.writeln("   \/\/打开窗口");
document.writeln(" ");
document.writeln("  <\/script>")